# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # use php 7.1 as the primary docker images for testing
      - image: circleci/php:7.1-apache-node-browsers

      # use mysql 5.6 with a tmpfs mount for faster tests
      - image: circleci/mysql:5.6-ram

    working_directory: ~/repo

    steps:
      - checkout

      # install application dependencies with composer
      - run: composer install -n --prefer-dist

      # install mysql-client this is just for ssh into box
      - run: sudo apt install mysql-client

      # download ngrok
      - run: /home/circleci/repo/ngrok.sh

      # run tests!
      - run: echo $(pwd)
      - run: echo $CIRCLE_BRANCH
      - run: echo $LOOKER_API_CREDENTIALS
      - run: echo $NGROK_AUTH_TOKEN
      - run: kill $(pgrep ngrok)
